version: "3.7"

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

  # Kong Migrations (runs once and exits)
  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    command: "kong migrations bootstrap"
    restart: "no"

  # Kong API Gateway
  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migrations
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong

      # Logging
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

      # Listener configuration
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
    ports:
      - "8000:8000" # HTTP Proxy
      - "8443:8443" # HTTPS Proxy
      - "127.0.0.1:8001:8001" # Admin HTTP
      - "127.0.0.1:8444:8444" # Admin HTTPS
      - "127.0.0.1:9080:9080" # HTTP2
      - "127.0.0.1:9081:9081" # HTTPS2
    restart: always

  # Konga Admin GUI
  konga:
    image: pantsel/konga
    container_name: konga
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: konga
      NODE_ENV: development # IMPORTANT: to populate the database
      DB_AUTO_MIGRATE: "true"
    ports:
      - "1337:1337"
    restart: on-failure

networks:
  kong-net:
    driver: bridge
