version: "3.7"

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    networks:
      - kong-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

  # Kong Migrations (runs once and exits)
  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    command: "kong migrations bootstrap"
    restart: "no"

  # Kong API Gateway
  kong:
    image: kong:latest
    container_name: kong
    depends_on:
      - kong-migrations
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong

      # Logging
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

      # Listener configuration
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:9080 http2, 0.0.0.0:9081 http2 ssl
    ports:
      - "8000:8000" # HTTP Proxy
      - "8443:8443" # HTTPS Proxy
      - "127.0.0.1:8001:8001" # Admin HTTP
      - "127.0.0.1:8444:8444" # Admin HTTPS
      - "127.0.0.1:9080:9080" # HTTP2
      - "127.0.0.1:9081:9081" # HTTPS2
    restart: always

  # Konga Admin GUI
  konga:
    image: pantsel/konga
    container_name: konga
    depends_on:
      - kong-database
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: konga
      NODE_ENV: development # IMPORTANT: to populate the database
      DB_AUTO_MIGRATE: "true"
    ports:
      - "1337:1337"
    restart: on-failure

    # --- MongoDB Database ---
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    networks:
      - kong-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: restaurant_db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Mongo Express (MongoDB GUI) ---
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    networks:
      - kong-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy

  # --- Restaurants Service ---
  restaurants-server:
    image: node:22-alpine
    container_name: restaurants-server
    working_dir: /app
    command: sh -c "npm install && npm run server"
    networks:
      - kong-net
    environment:
      PORT: 30043
      MONGODB_URI: mongodb://root:example@mongodb:27017/restaurant_db?authSource=admin
    ports:
      - "30043:30043"
    volumes:
      - ./restaurants:/app
      - /app/node_modules
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy

  restaurants-client:
    image: node:22-alpine
    container_name: restaurants-client
    working_dir: /app
    command: sh -c "npm install && npm run client"
    networks:
      - kong-net
    environment:
      PORT: 3000
      SERVICE_API_URL: kong:8000
    ports:
      - "3000:3000"
    volumes:
      - ./restaurants:/app
      - /app/node_modules
    restart: on-failure
    depends_on:
      restaurants-server:
        condition: service_started

networks:
  kong-net:
    driver: bridge
